### PR TITLE
Verified user

### PR DESCRIPTION
**Pull request by pierreozoux**

### CODE REVIEW

**Comment by michielbdejong** [comment]
I now see 'please sign in' and signed in as 'michiel@...' at the same time :) 
please-sign-in

**Comment by michielbdejong** [comment]
Oh, it's actually only confusing on the main page, the others have a good warning now. So maybe change 'Please sign in to submit or moderate points.' to 'Please sign in with a verified account to submit or moderate points (newly created users: check your email!).'

**Comment by michielbdejong** [comment]
Actually it would be better to have three situations:
- not logged in at all: 'Please sign in to submit or moderate points.'
- logged in with an unverified account: 'Please verify your account to proceed'
- logged in and verified: 'Please select an action from the menu' or something like that.

**Comment by pierreozoux** [comment]
Ok, this is fixed by: https://github.com/tosdr/tosdr2/commit/51bdf326c0895c71a6f90c5dd3051bc9f8f500c6

**Pull request merged**
